# Generated by Django 2.2.6 on 2019-12-12 14:40

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staticPages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=1, verbose_name='Порядок отображения')),
                ('image', models.ImageField(upload_to='banners/', verbose_name='Картинка')),
                ('smallText', models.CharField(max_length=255, verbose_name='Маленький текст')),
                ('bigText', models.CharField(max_length=255, verbose_name='Большой текст')),
                ('buttonText', models.CharField(max_length=255, verbose_name='Надпись на кнопке')),
                ('buttonUrl', models.CharField(max_length=255, verbose_name='Ссылка с кнопки')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Баннер',
                'verbose_name_plural': 'Баннеры',
            },
        ),
        migrations.CreateModel(
            name='Faq',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.ImageField(null=True, upload_to='sponsor_img/', verbose_name='Вопрос)')),
                ('answer', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Ответ')),
                ('isVip', models.BooleanField(default=True, verbose_name='Выводить на странице')),
            ],
            options={
                'verbose_name': 'Вопрос - Ответ',
                'verbose_name_plural': 'Вопросы - Ответы',
            },
        ),
    ]
