# Generated by Django 2.2.6 on 2019-12-12 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staticPages', '0002_banner_faq'),
    ]

    operations = [
        migrations.RenameField(
            model_name='faq',
            old_name='isVip',
            new_name='isActive',
        ),
        migrations.AlterField(
            model_name='faq',
            name='question',
            field=models.CharField(max_length=255, null=True, verbose_name='Вопрос'),
        ),
    ]
