# Generated by Django 2.2.7 on 2019-12-24 11:02

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staticPages', '0003_auto_20191212_1852'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True, verbose_name='ФИО')),
                ('image', models.ImageField(null=True, upload_to='post_img/', verbose_name='Изображение для поста')),
                ('nameSlug', models.CharField(blank=True, db_index=True, max_length=255, null=True, unique=True)),
                ('views', models.IntegerField(default=0, verbose_name='Просмотров')),
                ('about', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('fullText', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Содержание поста')),
                ('isAtHome', models.BooleanField(default=False, verbose_name='Отображать на главной?')),
            ],
            options={
                'verbose_name': 'Пост',
                'verbose_name_plural': 'Посты',
            },
        ),
    ]
