# Generated by Django 2.2.6 on 2019-12-24 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staticPages', '0004_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='author',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True, unique=True, verbose_name='Автор'),
        ),
        migrations.AddField(
            model_name='post',
            name='date',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True, unique=True, verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='post',
            name='name',
            field=models.CharField(max_length=255, null=True, verbose_name='Название'),
        ),
    ]
