# Generated by Django 3.1 on 2020-11-13 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staticPages', '0009_staticpage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quote', models.CharField(max_length=255, null=True, verbose_name='Цитата')),
                ('name', models.CharField(max_length=255, null=True, verbose_name='Отзыв от')),
                ('image', models.ImageField(null=True, upload_to='post_img/', verbose_name='Аватарка от кого отзыв')),
                ('text', models.TextField(blank=True, null=True, verbose_name='Текст')),
                ('is_active', models.BooleanField(default=True, verbose_name='Отображать?')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
            },
        ),
    ]
