# Generated by Django 3.1 on 2020-11-14 05:10

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staticPages', '0011_auto_20201114_0506'),
    ]

    operations = [
        migrations.CreateModel(
            name='MailSubscribe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=255, null=True, verbose_name='E-Mail')),
            ],
            options={
                'verbose_name': 'Подписка на рассылку',
                'verbose_name_plural': 'Подписки на рассылку',
            },
        ),
        migrations.AddField(
            model_name='staticpage',
            name='index_about_image',
            field=models.ImageField(null=True, upload_to='img/', verbose_name='Изображение на главной странице - Информация'),
        ),
        migrations.AddField(
            model_name='staticpage',
            name='index_about_text',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='Текст на главной странице - Информация'),
        ),
        migrations.AlterField(
            model_name='staticpage',
            name='apply_text',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='Текст на странице - Стать участником'),
        ),
    ]
