# Generated by Django 2.2.7 on 2019-12-11 06:44

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Speaker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True, verbose_name='Имя')),
                ('family', models.CharField(max_length=255, null=True, verbose_name='Фамилия')),
                ('nickName', models.CharField(max_length=255, null=True, verbose_name='Ник')),
                ('photo', models.ImageField(null=True, upload_to='speaker_img/', verbose_name='Фото)')),
                ('pageHeader', models.ImageField(null=True, upload_to='speaker_img/', verbose_name='Изображение для шапки страницы')),
                ('nickNameSlug', models.CharField(blank=True, db_index=True, max_length=255, null=True, unique=True)),
                ('linkVK', models.CharField(blank=True, default='Не указано', max_length=255, null=True, verbose_name='Ссылка на VK')),
                ('linkTW', models.CharField(blank=True, default='Не указано', max_length=255, null=True, verbose_name='Ссылка на Twitch')),
                ('linkYT', models.CharField(blank=True, default='Не указано', max_length=255, null=True, verbose_name='Ссылка на YouTube')),
                ('linkIN', models.CharField(blank=True, default='Не указано', max_length=255, null=True, verbose_name='Ссылка на Instagram')),
                ('views', models.IntegerField(default=0, verbose_name='Просмотров профиля')),
                ('buys', models.IntegerField(default=0, verbose_name='Покупок')),
                ('about', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Описание')),
                ('isAtHome', models.BooleanField(default=False, verbose_name='Отображать на главной?')),
            ],
            options={
                'verbose_name': 'Стример',
                'verbose_name_plural': 'Стримеры',
            },
        ),
    ]
