# Generated by Django 2.2.6 on 2019-12-15 10:44

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speaker', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='speaker',
            name='family',
        ),
        migrations.AddField(
            model_name='speaker',
            name='streaming',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Что стримит'),
        ),
        migrations.AlterField(
            model_name='speaker',
            name='name',
            field=models.CharField(max_length=255, null=True, verbose_name='ФИО'),
        ),
    ]
