# Generated by Django 2.2.7 on 2019-12-23 11:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('speaker', '0003_defaultitem_streameritem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='streameritem',
            options={'verbose_name': 'Билет от стримера', 'verbose_name_plural': 'Билеты от стримеров'},
        ),
        migrations.AlterField(
            model_name='defaultitem',
            name='articleOneDay',
            field=models.CharField(blank=True, default='one_day_pass', max_length=100, null=True, verbose_name='ID билета за 1 день'),
        ),
        migrations.AlterField(
            model_name='defaultitem',
            name='articleTwoDays',
            field=models.CharField(blank=True, default='two_days_pass', max_length=100, null=True, verbose_name='ID билета за 2 дня'),
        ),
        migrations.AlterField(
            model_name='defaultitem',
            name='priceTwoDays',
            field=models.IntegerField(default=0, verbose_name='Цена за 2 дня'),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customerFio', models.CharField(max_length=255, null=True, verbose_name='ФИО покупателя')),
                ('customerPhone', models.CharField(max_length=255, null=True, verbose_name='Телефон покупателя')),
                ('customerEmail', models.CharField(max_length=255, null=True, verbose_name='E-Mail покупателя')),
                ('isPayed', models.BooleanField(default=False, verbose_name='Оплачено')),
                ('createdAt', models.DateTimeField(auto_now_add=True, verbose_name='Заказ создан')),
                ('updatedAt', models.DateTimeField(auto_now=True, verbose_name='Заказ изменен')),
                ('defaultItem', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='speaker.DefaultItem', verbose_name='Обычный билет')),
                ('streamerItem', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='speaker.StreamerItem', verbose_name='Билет от стримера')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
    ]
