# Generated by Django 2.2.7 on 2019-12-23 12:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('speaker', '0004_auto_20191223_1446'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article', models.CharField(blank=True, db_index=True, max_length=100, null=True, verbose_name='Артикул')),
                ('isDefaultOneDayTicket', models.BooleanField(db_index=True, default=False, verbose_name='Это билет на 1 день?')),
                ('oneDayPrice', models.IntegerField(default=0, verbose_name='Цена  билета за 1 день. Эта цена будет применена ко всем билетам')),
                ('isDefaultTwoDayTicket', models.BooleanField(db_index=True, default=False, verbose_name='Это билет на 2 дня?')),
                ('twoDayPrice', models.IntegerField(default=0, verbose_name='Цена билета за 2 дня. Эта цена будет применена ко всем билетам')),
            ],
            options={
                'verbose_name': 'Билет',
                'verbose_name_plural': 'Билеты',
            },
        ),
        migrations.RemoveField(
            model_name='streameritem',
            name='streamer',
        ),
        migrations.RemoveField(
            model_name='order',
            name='defaultItem',
        ),
        migrations.RemoveField(
            model_name='order',
            name='streamerItem',
        ),
        migrations.AlterField(
            model_name='speaker',
            name='nickName',
            field=models.CharField(db_index=True, max_length=255, null=True, verbose_name='Ник'),
        ),
        migrations.DeleteModel(
            name='DefaultItem',
        ),
        migrations.DeleteModel(
            name='StreamerItem',
        ),
        migrations.AddField(
            model_name='ticket',
            name='streamer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_item', to='speaker.Speaker', verbose_name='Билет от стримера'),
        ),
        migrations.AddField(
            model_name='order',
            name='ticket',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='speaker.Ticket', verbose_name='Заказан'),
        ),
    ]
