# Generated by Django 2.2.7 on 2019-12-24 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speaker', '0007_auto_20191223_1807'),
    ]

    operations = [
        migrations.AddField(
            model_name='speaker',
            name='orderPP',
            field=models.IntegerField(default=10, verbose_name='Номер ПП'),
        ),
    ]
