# Generated by Django 2.2.7 on 2019-12-25 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speaker', '0008_speaker_orderpp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speaker',
            name='linkIN',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Ссылка на Instagram'),
        ),
        migrations.AlterField(
            model_name='speaker',
            name='linkTW',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Ссылка на Twitch'),
        ),
        migrations.AlterField(
            model_name='speaker',
            name='linkVK',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Ссылка на VK'),
        ),
        migrations.AlterField(
            model_name='speaker',
            name='linkYT',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Ссылка на YouTube'),
        ),
    ]
