# Generated by Django 2.2.7 on 2019-12-25 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speaker', '0009_auto_20191225_1526'),
    ]

    operations = [
        migrations.AddField(
            model_name='speaker',
            name='uniqUrl',
            field=models.CharField(blank=True, editable=False, max_length=100, null=True, verbose_name='Хеш для ссылки'),
        ),
    ]
