# Generated by Django 2.2.6 on 2020-01-15 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speaker', '0013_auto_20200106_2047'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='codeQR',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Случайное число для QR кода'),
        ),
        migrations.AddField(
            model_name='order',
            name='isCheckIn',
            field=models.BooleanField(default=False, verbose_name='Погашен'),
        ),
        migrations.AddField(
            model_name='order',
            name='isSpecial',
            field=models.BooleanField(default=False, verbose_name='Специальный заказ'),
        ),
    ]
